Repository cse110-w21-group7/cse110-SP21-group7, pull requests merged in 2021-06, with the labels that each got.

#268 Mulitple UI fixes
  package-lock.json
  source/css/collection-edit.css
  source/css/collection.css
  source/css/daily.css
  source/css/index.css
  source/css/weekly.css
  source/html/collection-edit.html
  source/html/collection.html
  source/html/daily.html
  source/html/index.html
  source/html/weekly.html
  source/javascript/src/collection-edit.js
  source/javascript/src/collection.js
  source/javascript/src/components/CollectionItem.js
  source/javascript/src/components/LogItem.js
  source/javascript/src/components/MediaItem.js
  source/javascript/src/components/ReflectionItem.js
  source/javascript/src/components/WeeklyViewItem.js
  source/javascript/src/components/book.js
  source/javascript/src/daily.js
  source/javascript/src/index.js
  source/javascript/src/weekly.js
  source/less/animation.less
  source/models/mock_data.json
  source/target/animation.css
  source/target/index.html
Labels: HTML (Frontend), JavaScript (Frontend)

#277 Added an issue template for bugs
  .github/ISSUE_TEMPLATE/bug-template.md
Labels: documentation, enhancement

#281 fixed issue 280
  source/javascript/src/collection-edit.js
Labels: Backend

#282 Fixed weekly view offsetting column days
  source/javascript/src/weekly.js
  source/models/mock_data.json
Labels: JavaScript (Frontend), bug

#293 Implement functionality for collection tags
  source/css/collection.css
  source/css/daily.css
  source/html/daily.html
  source/javascript/src/collection.js
  source/javascript/src/components/CollectionItem.js
  source/javascript/src/components/book.js
  source/javascript/src/components/tag.js
  source/javascript/src/daily.js
  source/models/mock_data.json
Labels: Backend, HTML (Frontend), JavaScript (Frontend), enhancement

#305 Searchitem component styling implemented
  source/css/collection-edit.css
  source/css/daily.css
  source/css/search.css
  source/html/collection-edit.html
  source/html/search.html
  source/javascript/src/components/SearchItem.js
  source/javascript/src/search.js
Labels: HTML (Frontend)

#279 Defining no log existing behavior
  source/html/daily.html
  source/javascript/src/daily.js
Labels: Backend

#310 Fix collection tags and fix styling issue with date on daily log page.
  source/css/daily.css
  source/html/daily.html
  source/javascript/src/collection.js
  source/javascript/src/components/CollectionItem.js
  source/javascript/src/daily.js
Labels: HTML (Frontend), bug

#317 UI Improvement on collection-edit, daily, and weekly
  admin/standups/standup_jun3.md
  source/css/collection-edit.css
  source/css/daily.css
  source/html/daily.html
  source/javascript/src/collection-edit.js
  source/javascript/src/components/LogItem.js
  source/javascript/src/components/MediaItem.js
  source/javascript/src/components/ReflectionItem.js
  source/javascript/src/components/WeeklyViewItem.js
  source/javascript/src/daily.js
Labels: HTML (Frontend), enhancement

#312 Update database when adding and deleting new tasks and checking/unchecking tasks
  source/html/collection-edit.html
  source/javascript/src/collection-edit.js
  source/javascript/src/components/LogItem.js
Labels: Backend

#314 Fixed duplicate collection tags bug
  source/javascript/src/daily.js
Labels: JavaScript (Frontend), bug

#284 unit testing for DateConverter and Weekly View styling
  .babelrc
  .github/workflows/node.js.yml
  package-lock.json
  package.json
  source/css/weekly.css
  source/html/weekly.html
  source/javascript/src/utils/DateConverter.js
  source/javascript/tests/date-converter.test.js
  source/javascript/tests/indexed-db-wrapper.test.js
Labels: HTML (Frontend), Testing/QA

#327 Fixed issue of an empty task being pushed to database
  source/javascript/src/collection-edit.js
Labels: Backend

#332 Team md update with picture
  admin/photos/Noah-pic.jpg
  admin/team.md
Labels: documentation

#346 Upload Alvin photo and put into team.md
  admin/photos/Alvin-pic.jpg
  admin/team.md
Labels: documentation

#356 Integrated changes with CD pipeline for deployment and minification
  .github/workflows/cd.yml
  .github/workflows/node.js.yml
  gulpfile.js
  package-lock.json
  package.json
  source/collection-edit.html
  source/collection.html
  source/daily.html
  source/index.html
  source/javascript/src/calendar.js
  source/javascript/src/components/CollectionItem.js
  source/javascript/src/components/LogItem.js
  source/javascript/src/components/MediaItem.js
  source/javascript/src/components/ReflectionItem.js
  source/javascript/src/daily.js
  source/javascript/src/index.js
  source/javascript/src/indexedDB/IndexedDBWrapper.js
  source/javascript/src/search.js
  source/javascript/src/utils/DateConverter.js
  source/javascript/src/utils/Router.js
  source/javascript/src/weekly.js
  source/javascript/tests/date-converter.test.js
  source/search.html
  source/source.md
  source/weekly.html
Labels: CI/CD

#364 Added new file to demo CI
  newFile.txt
Labels: CI/CD

#365 Updated route for production
  source/javascript/src/utils/Router.js
Labels: HTML (Frontend), JavaScript (Frontend)

#368 Added favicon for site
  source/collection-edit.html
  source/collection.html
  source/daily.html
  source/images/favicons/android-chrome-192x192.png
  source/images/favicons/android-chrome-512x512.png
  source/images/favicons/apple-touch-icon.png
  source/images/favicons/browserconfig.xml
  source/images/favicons/favicon-16x16.png
  source/images/favicons/favicon-32x32.png
  source/images/favicons/favicon.ico
  source/images/favicons/mstile-150x150.png
  source/images/favicons/safari-pinned-tab.svg
  source/images/favicons/site.webmanifest
  source/index.html
  source/search.html
  source/weekly.html
Labels: HTML (Frontend), enhancement

#371 Add documentation for daily.js
  source/javascript/src/daily.js
Labels: documentation

#372 Fixing onboard/adding my pic
  admin/onboard-images/CoverageTest.jpg
  admin/onboard-images/Front-Page.jpg
  admin/team.md
  onboard.md
Labels: documentation

#370 Add Katherine Picture
  admin/photos/Katherine-pic.png
  admin/team.md
Labels: documentation

#378 Cleanup code and update filepath
  source/javascript/src/components/book.js
  source/javascript/src/components/shelf.js
  source/javascript/src/components/tag.js
  source/javascript/src/daily.js
  source/javascript/src/index.js
Labels: bug

#382 Changed order in which weekly view and daily log shows log items
  source/javascript/src/components/WeeklyViewItem.js
Labels: JavaScript (Frontend)

#381 Fixed search propmpt styling and collection media item display
  admin/meetings/060821-privateScript.md
  source/css/collection-edit.css
  source/css/search.css
  source/javascript/src/components/MediaItem.js
Labels: HTML (Frontend)

#384 Dynamic placeholder text on Daily Log page
  source/css/daily.css
  source/daily.html
  source/javascript/src/components/tag.js
  source/javascript/src/daily.js
Labels: HTML (Frontend), enhancement

#393 Fixed issue with fuzzy search not working for long strings.
  source/javascript/src/components/WeeklyViewItem.js
  source/javascript/src/components/tag.js
  source/javascript/src/search.js
  source/javascript/src/weekly.js
Labels: Backend, bug

#396 Fixed time formatting issue for LogItem.js
  source/javascript/src/components/LogItem.js
Labels: JavaScript (Frontend), bug

#401 Delete newFile.txt
  newFile.txt
Labels: documentation

#398 Fixed issue with data persistence for tasks on weekly view, UI adjustment to display the number of search results on `search.html`
  .gitignore
  package-lock.json
  package.json
  source/javascript/src/components/LogItem.js
  source/javascript/src/components/WeeklyViewItem.js
  source/javascript/src/daily.js
  source/javascript/src/search.js
  source/javascript/src/utils/DateConverter.js
  specs/programming_docs/docs.md
Labels: Backend, JavaScript (Frontend), bug

#404 Updated CI job for documentation generation on push
  .github/workflows/main.yml
Labels: CI/CD

#405 Added subtree push to `programming-docs` branch for documentation
  .github/workflows/ci_docs.yml
Labels: CI/CD

#406 Fixed syntax issue with CI job
  .github/workflows/ci_docs.yml
Labels: CI/CD

#403 Removed documentation generating on PR requests
  .github/workflows/node.js.yml
Labels: CI/CD

#402 E2E testing
  .eslintrc.json
  package-lock.json
  package.json
  source/daily.html
  source/index.html
  source/javascript/tests/e2e/collection-edit.test.js
  source/javascript/tests/e2e/daily.test.js
  source/javascript/tests/e2e/index.test.js
  source/javascript/tests/indexed-db-wrapper.test.js
  source/javascript/tests/unit_tests/date-converter.test.js
  specs/interface/wireframes/weekly-wireframe.png
Labels: Testing/QA

#408 E2E testing
  package.json
  source/index.html
Labels: Testing/QA

#410 Duplication collections fix
  source/javascript/src/collection.js
Labels: bug, enhancement

#412 Update daily.css
  source/css/daily.css
Labels: enhancement
